BACK_BUTTON = 'BACK'
MAN_BUTTON = 'M'
WOMAN_BUTTON = 'WOMN'

ACTIVITY_COEFFICIENT_12_BUTTON = '1.2'
ACTIVITY_COEFFICIENT_13_BUTTON = '1.375'
ACTIVITY_COEFFICIENT_15_BUTTON = '1.55'
ACTIVITY_COEFFICIENT_17_BUTTON = '1.725'
ACTIVITY_COEFFICIENT_19_BUTTON = '1.9'

true_weight = None
true_height = None
true_age = None
basal_metabolism = None


MEASUREMENTS_BUTTON = 'measurements'

DIRECTORY_BUTTON ='DIRCTRY'
MY_PROFILE_BUTTON = 'M_PROFL'
CALCULATION_CALORIES = 'CALC_CALO'
HELP_BUTTON = 'HLP'
SUBSCRIPTION_BUTTON = 'SUBSCR'
EXERCISES_BUTTON = 'EXRCSS'
SPORTS_NUTRITION_BUTTON = 'SPRTS_NTRITN'
COMPOSITION_BUTTON = 'COMPSITON'
ENCYCLOPEDIA_BUTTON = 'ENCCLPEDA'
HELP_TEXT_BUTTON = 'HLP_TXT'
EMAIL_BUTTON = 'EML'